/*
 * This file is generated by jOOQ.
 */
package jhi.applogger.database.codegen.tables.records;


import javax.annotation.Generated;

import jhi.applogger.database.codegen.tables.Ips;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IpsRecord extends UpdatableRecordImpl<IpsRecord> implements Record10<Integer, String, String, String, String, String, String, String, String, String> {

    private static final long serialVersionUID = -1189590488;

    /**
     * Setter for <code>apptracker_db.ips.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>apptracker_db.ips.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>apptracker_db.ips.ip_address</code>.
     */
    public void setIpAddress(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>apptracker_db.ips.ip_address</code>.
     */
    public String getIpAddress() {
        return (String) get(1);
    }

    /**
     * Setter for <code>apptracker_db.ips.country</code>.
     */
    public void setCountry(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>apptracker_db.ips.country</code>.
     */
    public String getCountry() {
        return (String) get(2);
    }

    /**
     * Setter for <code>apptracker_db.ips.country_code</code>.
     */
    public void setCountryCode(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>apptracker_db.ips.country_code</code>.
     */
    public String getCountryCode() {
        return (String) get(3);
    }

    /**
     * Setter for <code>apptracker_db.ips.city</code>.
     */
    public void setCity(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>apptracker_db.ips.city</code>.
     */
    public String getCity() {
        return (String) get(4);
    }

    /**
     * Setter for <code>apptracker_db.ips.latitude</code>.
     */
    public void setLatitude(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>apptracker_db.ips.latitude</code>.
     */
    public String getLatitude() {
        return (String) get(5);
    }

    /**
     * Setter for <code>apptracker_db.ips.longitude</code>.
     */
    public void setLongitude(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>apptracker_db.ips.longitude</code>.
     */
    public String getLongitude() {
        return (String) get(6);
    }

    /**
     * Setter for <code>apptracker_db.ips.hostname</code>.
     */
    public void setHostname(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>apptracker_db.ips.hostname</code>.
     */
    public String getHostname() {
        return (String) get(7);
    }

    /**
     * Setter for <code>apptracker_db.ips.provider</code>.
     */
    public void setProvider(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>apptracker_db.ips.provider</code>.
     */
    public String getProvider() {
        return (String) get(8);
    }

    /**
     * Setter for <code>apptracker_db.ips.state</code>.
     */
    public void setState(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>apptracker_db.ips.state</code>.
     */
    public String getState() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, String, String, String, String, String, String, String, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, String, String, String, String, String, String, String, String> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Ips.IPS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Ips.IPS.IP_ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Ips.IPS.COUNTRY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Ips.IPS.COUNTRY_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Ips.IPS.CITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Ips.IPS.LATITUDE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Ips.IPS.LONGITUDE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Ips.IPS.HOSTNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Ips.IPS.PROVIDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Ips.IPS.STATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getIpAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getCountry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getCountryCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getCity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getLatitude();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getLongitude();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getHostname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getProvider();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getIpAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCountry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getCountryCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getCity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getLatitude();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getLongitude();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getHostname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getProvider();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IpsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IpsRecord value2(String value) {
        setIpAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IpsRecord value3(String value) {
        setCountry(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IpsRecord value4(String value) {
        setCountryCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IpsRecord value5(String value) {
        setCity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IpsRecord value6(String value) {
        setLatitude(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IpsRecord value7(String value) {
        setLongitude(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IpsRecord value8(String value) {
        setHostname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IpsRecord value9(String value) {
        setProvider(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IpsRecord value10(String value) {
        setState(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IpsRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached IpsRecord
     */
    public IpsRecord() {
        super(Ips.IPS);
    }

    /**
     * Create a detached, initialised IpsRecord
     */
    public IpsRecord(Integer id, String ipAddress, String country, String countryCode, String city, String latitude, String longitude, String hostname, String provider, String state) {
        super(Ips.IPS);

        set(0, id);
        set(1, ipAddress);
        set(2, country);
        set(3, countryCode);
        set(4, city);
        set(5, latitude);
        set(6, longitude);
        set(7, hostname);
        set(8, provider);
        set(9, state);
    }
// @formatter:on
}
