/*
 * This file is generated by jOOQ.
 */
package jhi.applogger.database.codegen.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersIps implements Serializable {

    private static final long serialVersionUID = -36826146;

    private Integer id;
    private Integer usersId;
    private Integer ipsId;
    private Integer applicationsId;

    public UsersIps() {}

    public UsersIps(UsersIps value) {
        this.id = value.id;
        this.usersId = value.usersId;
        this.ipsId = value.ipsId;
        this.applicationsId = value.applicationsId;
    }

    public UsersIps(
        Integer id,
        Integer usersId,
        Integer ipsId,
        Integer applicationsId
    ) {
        this.id = id;
        this.usersId = usersId;
        this.ipsId = ipsId;
        this.applicationsId = applicationsId;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getUsersId() {
        return this.usersId;
    }

    public void setUsersId(Integer usersId) {
        this.usersId = usersId;
    }

    public Integer getIpsId() {
        return this.ipsId;
    }

    public void setIpsId(Integer ipsId) {
        this.ipsId = ipsId;
    }

    public Integer getApplicationsId() {
        return this.applicationsId;
    }

    public void setApplicationsId(Integer applicationsId) {
        this.applicationsId = applicationsId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UsersIps (");

        sb.append(id);
        sb.append(", ").append(usersId);
        sb.append(", ").append(ipsId);
        sb.append(", ").append(applicationsId);

        sb.append(")");
        return sb.toString();
    }
// @formatter:on
}
