/*
 * This file is generated by jOOQ.
 */
package jhi.applogger.database.codegen.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.types.UInteger;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Users implements Serializable {

    private static final long serialVersionUID = 347323639;

    private Integer   id;
    private Integer   applicationId;
    private String    userid;
    private String    userName;
    private String    version;
    private String    locale;
    private Timestamp date;
    private String    os;
    private UInteger  runCount;
    private UInteger  rating;

    public Users() {}

    public Users(Users value) {
        this.id = value.id;
        this.applicationId = value.applicationId;
        this.userid = value.userid;
        this.userName = value.userName;
        this.version = value.version;
        this.locale = value.locale;
        this.date = value.date;
        this.os = value.os;
        this.runCount = value.runCount;
        this.rating = value.rating;
    }

    public Users(
        Integer   id,
        Integer   applicationId,
        String    userid,
        String    userName,
        String    version,
        String    locale,
        Timestamp date,
        String    os,
        UInteger  runCount,
        UInteger  rating
    ) {
        this.id = id;
        this.applicationId = applicationId;
        this.userid = userid;
        this.userName = userName;
        this.version = version;
        this.locale = locale;
        this.date = date;
        this.os = os;
        this.runCount = runCount;
        this.rating = rating;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getApplicationId() {
        return this.applicationId;
    }

    public void setApplicationId(Integer applicationId) {
        this.applicationId = applicationId;
    }

    public String getUserid() {
        return this.userid;
    }

    public void setUserid(String userid) {
        this.userid = userid;
    }

    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getVersion() {
        return this.version;
    }

    public void setVersion(String version) {
        this.version = version;
    }

    public String getLocale() {
        return this.locale;
    }

    public void setLocale(String locale) {
        this.locale = locale;
    }

    public Timestamp getDate() {
        return this.date;
    }

    public void setDate(Timestamp date) {
        this.date = date;
    }

    public String getOs() {
        return this.os;
    }

    public void setOs(String os) {
        this.os = os;
    }

    public UInteger getRunCount() {
        return this.runCount;
    }

    public void setRunCount(UInteger runCount) {
        this.runCount = runCount;
    }

    public UInteger getRating() {
        return this.rating;
    }

    public void setRating(UInteger rating) {
        this.rating = rating;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Users (");

        sb.append(id);
        sb.append(", ").append(applicationId);
        sb.append(", ").append(userid);
        sb.append(", ").append(userName);
        sb.append(", ").append(version);
        sb.append(", ").append(locale);
        sb.append(", ").append(date);
        sb.append(", ").append(os);
        sb.append(", ").append(runCount);
        sb.append(", ").append(rating);

        sb.append(")");
        return sb.toString();
    }
// @formatter:on
}
